# Generated by Django 5.0.8 on 2024-11-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sangrov", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sns",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("no", models.BigIntegerField(verbose_name="No")),
                (
                    "delivery_date",
                    models.CharField(max_length=255, verbose_name="Delivery Date"),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=255, verbose_name="Customer Name"),
                ),
                (
                    "material_number",
                    models.CharField(max_length=255, verbose_name="Material Number"),
                ),
                (
                    "material_description",
                    models.CharField(
                        max_length=255, verbose_name="Material Description"
                    ),
                ),
                (
                    "shipped_quantity",
                    models.CharField(max_length=255, verbose_name="Shipped Quantity"),
                ),
                (
                    "serial_number",
                    models.CharField(max_length=255, verbose_name="Serial Number"),
                ),
            ],
            options={
                "verbose_name": "Sns",
                "verbose_name_plural": "Sns",
                "db_table": "sns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="data",
            name="warranty",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
