# Generated by Django 5.0.8 on 2024-11-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sangrov", "0002_sns_alter_data_warranty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sns",
            name="customer_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Customer Name"
            ),
        ),
        migrations.AlterField(
            model_name="sns",
            name="delivery_date",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Delivery Date"
            ),
        ),
        migrations.AlterField(
            model_name="sns",
            name="material_description",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Material Description",
            ),
        ),
        migrations.AlterField(
            model_name="sns",
            name="material_number",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Material Number"
            ),
        ),
        migrations.AlterField(
            model_name="sns",
            name="no",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="No"),
        ),
        migrations.AlterField(
            model_name="sns",
            name="serial_number",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Serial Number"
            ),
        ),
        migrations.AlterField(
            model_name="sns",
            name="shipped_quantity",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Shipped Quantity"
            ),
        ),
    ]
